name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:prod
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.HOST_NAME }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: dist
          REMOTE_DIR: my-digital-library.indemo.azhe.space
          ARGS: --delete --transfer-all
      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        env:
          TELEGRAM_TOKEN: ${{ secrets. TGBOT_AZHE_ASSISTANT }}
          TELEGRAM_TO: ${{ secrets. TGUSER_ME }}
        with:
          message: |
            The ${{ github.event_name }} event triggered final step.
            echo This event is a pull request that had an assignee removed.
